WIP

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,6 +38,7 @@ runs:
         ENVIRONMENT_DIRECTORY: environments/${{ inputs.environment }}
         ENVIRONMENT_KUSTOMIZATION_FILE: environments/${{ inputs.environment }}/kustomization.yaml
         ENVIRONMENT_TEMPLATE_FILE: etc/${{ inputs.environment }}/kustomization.yaml
+        GH_TOKEN: ${{ inputs.token }}
         REPOSITORY: ${{ inputs.repository }}
       working-directory: _delivery
       run: |
@@ -46,7 +47,8 @@ runs:
         [[ -z "${REPOSITORY}" ]] && echo "Missing repository input" && exit 1 
         [[ -z "${BRANCH}" ]] && echo "Missing branch input" && exit 1
         [[ -z "${ENVIRONMENT}" ]] && echo "Missing environment input" && exit 1
-        
+        [[ -z "${TOKEN}" ]] && echo "Missing token input" && exit 1
+
         # Ensure repository environment kustomization exists; create it if missing
         if [[ ! -f "${ENVIRONMENT_KUSTOMIZATION_FILE}" ]]; then
           mkdir -pv "environments/${ENVIRONMENT}"
@@ -73,6 +75,10 @@ runs:
         REPOS_DEPLOYED_EXPR='[.patches[] | select(.target.group=="source.toolkit.fluxcd.io" and .target.version=="v1" and .target.kind=="GitRepository")] | length'
         if [[ "$(yq e "${REPOS_DEPLOYED_EXPR}" "${ENVIRONMENT_KUSTOMIZATION_FILE}")" == "0" ]]; then
           git rm -rfv "${ENVIRONMENT_DIRECTORY}"
+          gh api --method DELETE \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "/repos/arikkfir/${REPOSITORY}/environments/${ENVIRONMENT}"
         fi
         
         # Remove this repository from the list of repositories monitored by the Flux webhook receiver (if it's there)
